### ISSUE TITLE
[Windows] PC not starting

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Delta2Force/MCVmComputers#1]
basically i setup the Memory (6GB with 128MB VRAM), made a harddrive, and got a Win7 ISO.
but when i click "turn on PC" the log in MultiMC spits this out: [PASTEBIN](https://pastebin.com/DaNrKYdR)
when closing the game it also shows this:
```
[22:01:29] [main/INFO]: [STDOUT]: Stopping VM Computers Mod...
[22:01:29] [main/INFO]: [STDOUT]: Stopped VM Computers Mod.
Exception in thread "Turn on PC" Exception in thread "Tablet Renderer" 
Process exited with code 0.
```
Information:
VBox:
VirtualBox v6.0.22, i had it before the mod but updated it before using the mod.
Minecraft:
Fabric v0.8.7+Build.201
VMComputers 1.2.0
MC was given 10GB of RAM
after starting the game i gave the VM 6GB of RAM and 128MB of VRAM
Host System:
OS: Win10 v2004
CPU: i7-7740X @ 4.5GHz
RAM: 24GB DDR4
GPU: GTX 1080 8GB

**Comment by Delta2Force** [comment]
Try updating to VirtualBox 6.1.x and see if it works

**Comment by ProxyPlayerHD** [comment]
well i'm stupid. i did update, my previous version was 6.0.20 and i thought 6.0.22 was the newest

it works now. maybe there should be something on the curse-page about a min. required Vbox version...

**Comment by Delta2Force** [comment]
Sorry, I'll fix it :)
