### ISSUE TITLE
Unable to detect/start Virtualbox even when installed on Solus

### ISSUE THREAD

**Issue by E404NNF** [Delta2Force/MCVmComputers#104]
Hey! I'm trying to go through the setup but it says it can't detect Virtualbox on my pc, what could be the issue?
Minecraft Log: https://paste.ee/p/GmUVj
`java -version` outpot:
`openjdk version "1.8.0_252-solus"
OpenJDK Runtime Environment (build 1.8.0_252-solus-ga)
OpenJDK 64-Bit Server VM (build 25.252-bga, mixed mode)`

**Comment by Busaruba2011** [comment]
Did you put the right directory in for virtual box? And if you have VMware, that's not supported. If not, reinstall the mod.

**Comment by E404NNF** [comment]
I installed it from my package manager, and as I stated, VirtualBox

**Comment by Busaruba2011** [comment]
> I installed it from my package manager, and as I stated, VirtualBox

And what's solus?

**Comment by E404NNF** [comment]
https://getsol.us/home/

**Comment by Busaruba2011** [comment]
> https://getsol.us/home/

Ah, I've never heard of that, so I don't know. Sorry!

**Comment by E404NNF** [comment]
> > https://getsol.us/home/
> 
> Ah, I've never heard of that, so I don't know. Sorry!

It's ok

**Comment by Delta2Force** [comment]
What is the VirtualBox version?

**Comment by E404NNF** [comment]
It was 6.x, will check later because can't multi task while rendering a video on core 2 duo

**Comment by E404NNF** [comment]
6.1.12_Solus r139365

**Comment by Delta2Force** [comment]
Try opening a terminal and entering „vboxwebsrv“, does anything happen?

**Comment by E404NNF** [comment]
` e404nnf@e404nnf-g41smpt  ~  vboxwebsrv
/usr/bin/vboxwebsrv: line 138: /usr/lib/virtualbox/vboxwebsrv: No such file or directory
`
this happens

**Comment by Delta2Force** [comment]
I guess this is an issue with how solus installs virtualbox, since the symlink /usr/bin/vboxwebsrv (which this mod uses) leads to a nonexistent file.

**Comment by E404NNF** [comment]
i downloaded a Debian image of VirtualBox from https://www.virtualbox.org/wiki/Download_Old_Builds_6_1 and then extracted the needed binary, i think closing this would be fine now
