### ISSUE TITLE
Can't use existing vdi files

### ISSUE THREAD

**Issue by Busaruba2011** [Delta2Force/MCVmComputers#109]
I put a vdi in the hard drives folder, but it wont let me put it in the pc. Is this intentional or is it a bug. Its a 10gb vdi with ubuntu 20.4 on it.

**Comment by Delta2Force** [comment]
So, you put the vdi into the Hard drives folder, you right clicked a hard drive ingame, went to select an existing one, and then?

**Comment by Busaruba2011** [comment]
> So, you put the vdi into the Hard drives folder, you right clicked a hard drive ingame, went to select an existing one, and then?

When I try to put it in the PC, it doesn't show up. I'll try now with a vdi with windows 8.1

**Comment by Busaruba2011** [comment]
> > So, you put the vdi into the Hard drives folder, you right clicked a hard drive ingame, went to select an existing one, and then?
> 
> When I try to put it in the PC, it doesn't show up. I'll try now with a vdi with windows 8.1

Still wont work with 8.1 vdi

**Comment by Delta2Force** [comment]
What do you mean by it doesn’t show up? So you selected your vdi and the Hard drive now has the name of your vdi, you right click the case, Open case, no vdi at the bottom right?

**Comment by Busaruba2011** [comment]
> What do you mean by it doesn’t show up? So you selected your vdi and the Hard drive now has the name of your vdi, you right click the case, Open case, no vdi at the bottom right?

Yeah, if you want I'll send a video

**Comment by Delta2Force** [comment]
Please do, what im thinking is that your custom vdi name has a space in it or something.

**Comment by Busaruba2011** [comment]
> Please do, what im thinking is that your custom vdi name has a space in it or something.

Ah, it does

**Comment by Delta2Force** [comment]
Does it work without the space?

**Comment by Busaruba2011** [comment]
No, it shows when I make a hdd in the game, but not in the pc

**Comment by Busaruba2011** [comment]
Sorry it's been a while!
I removed the space from the vdi name and its sorted
CLOSED
