### ISSUE TITLE
Game crashing when rightclicking the PC case

### ISSUE THREAD

**Issue by pivinx1** [Delta2Force/MCVmComputers#117]
Hello, 
My game crashes when I try to open the PC case.
I've attached an crashlog for information.
Also, I was running perfectly on an older version of the mod.
[crashlog.txt](https://github.com/Delta2Force/MCVmComputers/files/5433303/crashlog.txt)

**Comment by CoccodrillooXDS** [comment]
Hi! This mod needs Minecraft 1.15.2 (you are using 1.15.0).

**Comment by pivinx1** [comment]
Oh okay, thanks.

**Comment by CoccodrillooXDS** [comment]
No problem. Feel free to reopen the issue if this problem persists on Minecraft 1.15.2
