### ISSUE TITLE
Nothing happens after turning on the pc.

### ISSUE THREAD

**Issue by Fuzzy2700** [Delta2Force/MCVmComputers#118]
As the title says. I have Windows XP on the hard drive.
https://www.youtube.com/watch?v=_YzqxCsO6aw

**Comment by CoccodrillooXDS** [comment]
Does the VM start when started from Minecraft and normally? (You may check in VirtualBox)

**Comment by Fuzzy2700** [comment]
The virtual machine created by it was there but for some reason it was "incaccesible", any idea why?

**Comment by Busaruba2011** [comment]
Have you tried deleting the vmcomputers vm, then reinstalling the mod? If not, try it.

**Comment by Fuzzy2700** [comment]
Okay that worked, thank you :D

**Comment by Busaruba2011** [comment]
> Okay that worked, thank you :D

Alright!
