### ISSUE TITLE
Game crashes alot with MCVM installed

### ISSUE THREAD

**Issue by Busaruba2011** [Delta2Force/MCVmComputers#119]
My game crashes alot with this mod installed. I had adorn installed, so I got rid of it and that didnt help. I'm on Windows 10 Home.

**Comment by Delta2Force** [comment]
Can you send in some of the crash reports?

**Comment by Busaruba2011** [comment]
> Can you send in some of the crash reports?

I will when I go on my PC.
One of the main issues is when I teleport to a Village, it crashes saying 'Failed to load entity NBT data'

**Comment by Busaruba2011** [comment]
Here's one of the crash reports, it was on 8/11/2020 (UK date format, so november 8th) sorry it google docs, i dont have pastebin :)
https://docs.google.com/document/d/1F43GOqQ46ox_ByCtjcAEks4kjh2f7_haq5k3AbplIcI/edit?usp=sharing

**Comment by lc67846** [comment]
Yeah It Happens Every Time But I Have Not Tried The Latest Version Of The Mod Yet But I'm On Laptop And It Is Windows 10 Home Too But I Can Use Virtualbox By Its Self I May Have To Remove The Tablet Render Because That Is My Problem On my MC

**Comment by lc67846** [comment]
Or Make One On My Own And Remove The Tablet

**Comment by lc67846** [comment]
@Busaruba2011 Try A Diffrent World Because That Is A World Problem Not A Mod Problem The NBT Data Is A Part Of Enitys And Blocks Data And World Data

**Comment by Busaruba2011** [comment]
> @Busaruba2011 Try A Diffrent World Because That Is A World Problem Not A Mod Problem The NBT Data Is A Part Of Enitys And Blocks Data And World Data 

Fixed

**Comment by lc67846** [comment]
Why Close #199

**Comment by lc67846** [comment]
#58
