### ISSUE TITLE
Not showing item names in store GUI

### ISSUE THREAD

**Issue by OrangeTurtle197** [Delta2Force/MCVmComputers#127]

**Comment by Harry989** [comment]
I have the same issue. I've opened another Issue with an actual description.

**Comment by OrangeTurtle197** [comment]
> I have the same issue. I've opened another Issue with an actual description.

Screenshot would be provided, but GitHub won't let me upload one.

**Comment by Delta2Force** [comment]
> > I have the same issue. I've opened another Issue with an actual description.
> 
> Screenshot would be provided, but GitHub won't let me upload one.

Can you upload it using imgur?
