### ISSUE TITLE
Can't start minecraft

### ISSUE THREAD

**Issue by zirdum** [Delta2Force/MCVmComputers#13]
I'm on a Macbook Pro with 16GB RAM, running MacOS Catalina.

I load up Minecraft with the Fabric Loader 1.15.2. It starts with the 1/4 page, I click next and it skips the 2/4 page and immediately takes me to the 3/4 page (with the location of the vm folder), and on the 4/4 page it takes me to the memory config (8196 and 256). I click next and I get an error (see error.jpg). I've also attached the latest.log file.
![Error](https://user-images.githubusercontent.com/30192872/84617858-2867dc00-ae85-11ea-82bb-6b4f7b59f675.jpg)
[latest.log](https://github.com/Delta2Force/MCVmComputers/files/4778020/latest.log)

Any ideas what I'm doing wrong?

**Comment by Delta2Force** [comment]
Sorry, I didn't think about Mac users. I'll quickly stir up a fix.

**Comment by Delta2Force** [comment]
Why did I close lol

**Comment by Delta2Force** [comment]
Fixed in #15
