### ISSUE TITLE
add russian translate pls

### ISSUE THREAD

**Issue by MegaSa1nt** [Delta2Force/MCVmComputers#131]
i can help if you want

**Comment by MegaSa1nt** [comment]
my discord 🔥ℳℰ୮Ꭿℭℬ 尺 Ťℴ Ũ🔥#9096

**Comment by ItsK1tty** [comment]
Just translate it yourself in a localization file

**Comment by MegaSa1nt** [comment]
yeah im late
[ru_ru.txt](https://github.com/Delta2Force/MCVmComputers/files/6980534/ru_ru.txt)
but

**Comment by MegaSa1nt** [comment]
[ru_ru.zip](https://github.com/Delta2Force/MCVmComputers/files/6980550/ru_ru.zip)

**Comment by MegaSa1nt** [comment]
#267
