### ISSUE TITLE
cant start pc

### ISSUE THREAD

**Issue by MegaSa1nt** [Delta2Force/MCVmComputers#132]
i dont know why but when i start pc happens this

**Comment by MegaSa1nt** [comment]
![javaw_2eqNZopHt6](https://user-images.githubusercontent.com/49565695/98470125-84047e80-2205-11eb-9ed3-6df33074a496.png)
![explorer_PeYo1X2JRg](https://user-images.githubusercontent.com/49565695/98470127-8535ab80-2205-11eb-8aa1-f7f158f5b298.png)

**Comment by MegaSa1nt** [comment]
also i have this
![изображение](https://user-images.githubusercontent.com/49565695/98470280-671c7b00-2206-11eb-89d6-ca281cd4be88.png)

**Comment by MegaSa1nt** [comment]
about isos - im dumb

**Comment by Busaruba2011** [comment]
Try installing fabric to .minecraft\Fabric\1.15.2 or 1.16.3 depending on what version

**Comment by Delta2Force** [comment]
Try using a better CPU ingame (1/2 instead of 1/6)

**Comment by y2k04** [comment]
Duplicate of #45

**Comment by MegaSa1nt** [comment]
> Duplicate of #45

are you sure?

**Comment by y2k04** [comment]
Oops wrong word. Meant to say related
