### ISSUE TITLE
No internet on the vm

### ISSUE THREAD

**Issue by Busaruba2011** [Delta2Force/MCVmComputers#133]
I made a Windows 8.1 machine, only to find that the internet doesnt work. Windows 10 host, Windows 8.1 guest, VirtualBox 6.1.14, TP-Link Archer T1U network adapter (it's usb 2 btw)

**Comment by Delta2Force** [comment]
This can be fixed by changing the virtualized adapter in VirtualBox, the settings will be carried over.

**Comment by YourDLCMaster** [comment]
This was closed quite a long time ago, but I have tried changing the adapter to multiple different types from the dropdown menu and none of them work. My Windows XP VM is still offline.
