### ISSUE TITLE
wont work

### ISSUE THREAD

**Issue by Angel12345678f** [Delta2Force/MCVmComputers#134]
Could not find required mod: fabric requires {minecraft @ [~1.16.2-alpha.20.28.a]}

**Comment by Busaruba2011** [comment]
Have you got Fabric API?

**Comment by Delta2Force** [comment]
Are you using Minecraft 1.16.3?

**Comment by Busaruba2011** [comment]
> Could not find required mod: fabric requires {minecraft @ [~1.16.2-alpha.20.28.a]}

If you didn't already have Minecraft 1.16.3 installed, install it (VANILLA!!!)
I can see in the log you posted, you are using 1.16.2. You need 1.16.3 to run the mod.
