### ISSUE TITLE
mouse cursor not showing up

### ISSUE THREAD

**Issue by CBPolarBear** [Delta2Force/MCVmComputers#135]
when in focus, the mouse cursor still functions, however it does not show on the screen.

**Comment by Busaruba2011** [comment]
What OS is the guest and host? If the guest is Ubuntu, the mouse doesn't show up for anyone for some reason.

**Comment by CBPolarBear** [comment]
yes, im running the mod on windows 10, and the mod is running a distro of
ubuntu called linux mint.

**Comment by Delta2Force** [comment]
Yeah, that's a common issue with Linux OSs, don't really know why that happens

**Comment by Busaruba2011** [comment]
@Delta2Force I'll try with Ubuntu 20.10 and see if it works and get back to you.

**Comment by patcon** [comment]
@Busaruba2011 any update? Thanks :)

**Comment by y2k04** [comment]
Duplicate of #14
