### ISSUE TITLE
No internet on the VM

### ISSUE THREAD

**Issue by 3raden** [Delta2Force/MCVmComputers#137]
How do i fix the internet driver, i dont know how to get it on there.

**Comment by Busaruba2011** [comment]
I already posted this #133

**Comment by Delta2Force** [comment]
This is how you can fix it:

This can be fixed by changing the virtualized adapter in VirtualBox, the settings will be carried over.

_Originally posted by @Delta2Force in https://github.com/Delta2Force/MCVmComputers/issues/133#issuecomment-728133683_
