### ISSUE TITLE
Add This Pls

### ISSUE THREAD

**Issue by lc67846** [Delta2Force/MCVmComputers#139]
You Should Add Routers So We Can Do Stuff Online And It Is A Part Of The Motherboard

**Comment by MegaSa1nt** [comment]
+

**Comment by lc67846** [comment]
So Will You Add It?

**Comment by lc67846** [comment]
:reply Add It To The Mod

**Comment by lc67846** [comment]
Or Will I Have To

**Comment by lc67846** [comment]
#58

**Comment by lc67846** [comment]
#closed

**Comment by kristibektashi** [comment]
You're very annoying. Just shut up. Linux is just as good as Windows

**Comment by lc67846** [comment]
shut up

**Comment by lc67846** [comment]
And No It Is Not I Have Tryed It Before

**Comment by lc67846** [comment]
So Yeah But I Will Give You A Linux Bundle If You Be Nice And I Have A Hidden Version Of The Mod That No One Has Even The Owner

**Comment by kristibektashi** [comment]
Actually your idea is pretty good. Routers would be a nice addition to the mod

**Comment by lc67846** [comment]
Thanks
