### ISSUE TITLE
1.16.4 support?

### ISSUE THREAD

**Issue by kristibektashi** [Delta2Force/MCVmComputers#143]

**Comment by Delta2Force** [comment]
I'll do it this afternoon.

**Comment by kristibektashi** [comment]
Still waiting

**Comment by Delta2Force** [comment]
Ahh i forgot! I'm working on it right now

**Comment by kristibektashi** [comment]
Could you make a release or do I have to build it myself?

**Comment by kristibektashi** [comment]
Also maybe you could update qemu branch to 1.16?
