### ISSUE TITLE
VMware could maybe be possible

### ISSUE THREAD

**Issue by privatedev11** [Delta2Force/MCVmComputers#148]
# VMware could be possible
VMware has a webpage here saying about their APIs and SDKs. https://www.vmware.com/support/pubs/sdk_pubs.html
It says on one of them about Java.
I'll have a look for some open source stuff about VMware 😄

**Comment by Busaruba2011** [comment]
They have a GitHub acc: github.com/vmware

**Comment by BlueJay113** [comment]
https://github.com/vmware/open-vm-tools
https://sourceforge.net/projects/open-vm-tools/

This is what you would probably want to look at, seems like something that would be helpful (in the slightest).

**Comment by KirbyTheStar9** [comment]
yes

**Comment by lc67846** [comment]
Yeah This Just My Opin But I Use VMware For a living and i think virtualbox sucks because you cant do the iso from the start of create

**Comment by Busaruba2011** [comment]
> Yeah This Just My Opin But I Use VMware For a living and i think virtualbox sucks because you cant do the iso from the start of create

VirtualBox is ok but vmware is just better i think

**Comment by lc67846** [comment]
Same

**Comment by y2k04** [comment]
I'll do some reading, yes I know this was abandoned, but it would be good to at least try and revive it?

**Comment by privatedev11** [comment]
> I'll do some reading, yes I know this was abandoned, but it would be good to at least try and revive it?

Yeah that sounds good

**Comment by y2k04** [comment]
Duplicate of #80
