### ISSUE TITLE
Items not showing up on the ordering tablet

### ISSUE THREAD

**Issue by CM436** [Delta2Force/MCVmComputers#156]
![2021-01-23_12 24 52](https://user-images.githubusercontent.com/53280799/105610558-cbff6000-5d75-11eb-94a6-227bebb2f92a.png)
The tablet itself works, you just can't see anything you're buying.

**Comment by moglol** [comment]
same im really confused

**Comment by moglol** [comment]
![image](https://user-images.githubusercontent.com/70176674/105712546-d9515180-5f11-11eb-9835-4c8b71805568.png)

**Comment by Scwestbrook** [comment]
This is only in 1.16.3, use the Curseforge app to launch 1.15.2, and you're good to go.

**Comment by Scwestbrook** [comment]
You're in creative, just grab the items from your inventory

**Comment by Scwestbrook** [comment]
Grab one of everything- Provided you have a LOT of iron ingots.

**Comment by MCAlexisYT** [comment]
Same...

**Comment by y2k04** [comment]
Duplicate of #127
