### ISSUE TITLE
Fabric logs say the mod is not a fabric mod

### ISSUE THREAD

**Issue by Alphim** [Delta2Force/MCVmComputers#158]
Ok, when I was starting minecraft after getting the .jar file in the mods folder, it didn't have the setup nor mod in it
Then i looked at the logs, and it said "Non-Fabric mod JAR at "C:\Users\(private user)\AppData\Roaming\.minecraft\mods\mcvmcomputers-1.4.13-dev.jar", ignoring" I tried running the mod on forge. I check to see if it works on forge, and I see that forge said its not a valid mod file. Please dear god help.

**Comment by Busaruba2011** [comment]
Try using an older version of the mod. If that doesnt work, use a new
fabric installation.

**Comment by CoccodrillooXDS** [comment]
@Alphim you inserted the "*-dev.jar" file in your mods folder. It doesn't work with Fabric. (try with another .jar file)

**Comment by Alphim** [comment]
@CoccodrillooXDS Exactly which?

**Comment by CoccodrillooXDS** [comment]
@Alphim Do you build the mod by yourself? If so:
> When you build the mod you get 4 files like this:
> ![image](https://user-images.githubusercontent.com/25722501/105741169-4a0c6400-5f3a-11eb-9343-480012442b87.png)
> You need the first one (selected in the image)

If not, try to download the mod from the "Releases" page

**Comment by Alphim** [comment]
@CoccodrillooXDS Thanks! im closing the thread now.
