### ISSUE TITLE
Limited to only 1 CPU core in Guest OS

### ISSUE THREAD

**Issue by log1xx** [Delta2Force/MCVmComputers#161]
Running version 1.16.3
Running on i7-9700k (8 Cores)
Host OS: Windows 10 Pro
Guest OS: Windows 10 Pro/Ubuntu

Issue: CPU limited to only 1 core in the Guest OS. even when using the 1/2, 1/4, and 1/6 Host CPUs in the mod. This seems like an issue on both Windows and Linux Guest OS. Manually changing it up to 4 Cores (1/2 of my Host CPU) also does not work.

**Comment by Busaruba2011** [comment]
If you add a 1/4 cpu, does the VmComputersvm change?

**Comment by Half-Life-3** [comment]
> 
> 
> If you add a 1/4 cpu, does the VmComputersvm change?

It appears to set the vm to use 1 cpu on boot regardless of the host CPU module installed.

(Ryzen 5 5600X 6 core, Windows 10 home host, Ubuntu 20.04 guest)
