### ISSUE TITLE
Hard Drives Not Appearing

### ISSUE THREAD

**Issue by MCAlexisYT** [Delta2Force/MCVmComputers#166]
![MC VM Issue 2](https://user-images.githubusercontent.com/78766083/107405732-9d9fb580-6ad5-11eb-8841-3a1b39e098fe.PNG)
Why is there so many "bedrock walls" that prevents me from starting a VM in Minecraft for even the first time? Probably due to me having to delete the Fabric Loader .jar file after it being corrupted.

**Comment by MCAlexisYT** [comment]
Welp, this ended up being issue #166...

**Comment by lc67846** [comment]
Weird

**Comment by lc67846** [comment]
And Thats becuase You did not setup the hard 
drive

**Comment by MCAlexisYT** [comment]
>You did not setup the hard drive

I just CAN'T understand why anyone would judge me in my face over the slightest issue.

**Comment by MCAlexisYT** [comment]
Never the less, it DID work! Thank you, @lc67846 !
😉
