### ISSUE TITLE
Is this repository still active?

### ISSUE THREAD

**Issue by kristibektashi** [Delta2Force/MCVmComputers#168]

**Comment by Delta2Force** [comment]
I have pretty much halted developing the mod as I'm focusing on different projects and schoolwork right now, pull requests and the like I (or @CoccodrillooXDS) am still going to respond to once in a while, but at this point it's not really as active as it was back when I launched it.

**Comment by kristibektashi** [comment]
@Delta2Force At least can you update to 1.16.5?

**Comment by kristibektashi** [comment]
@Delta2Force At least can you make a 1.16.4 release (and put it on releases page) so that I don't have to compile myself?

**Comment by Delta2Force** [comment]
I just released the 1.16.5 build on curseforge and on here too :)
