### ISSUE TITLE
input contains spaces

### ISSUE THREAD

**Issue by BmoreKarl** [Delta2Force/MCVmComputers#170]
trying to fill in "VM Computers directory" on setup page 3/5, my file directory includes the name of the user on my windows computer, and i have it as my first name space last name. How do I fix this? the directory in question is C:\Users\Jonathan Hille\AppData\Roaming\.minecraft\vm_computers Is there something else wrong?

**Comment by CoccodrillooXDS** [comment]
This is a problem. The only workaround for now is to use another folder outside your profile directory (for example C:\vm_computers).

**Comment by CoccodrillooXDS** [comment]
This is a problem that needs a fix, don't close the issue.
