### ISSUE TITLE
Game Will crash with mod installed 

### ISSUE THREAD

**Issue by PokeyManatee4** [Delta2Force/MCVmComputers#171]

**Comment by lc67846** [comment]
I don't have the log right now

**Comment by lc67846** [comment]
But I know it said the tablet model

**Comment by Delta2Force** [comment]
Please upload the log when you can.

**Comment by lc67846** [comment]
Ok It Will Will Be On The weekend because the computer is at my mom's and
I'm at my dad's

**Comment by lc67846** [comment]
I cant find the log

**Comment by Delta2Force** [comment]
It's at .minecraft/logs/latest.log. Please reproduce the issue and then upload that file

**Comment by lc67846** [comment]
No It Was A While Back A Go And There Was Not A Thing There

**Comment by hdfsyu** [comment]
@lc67846 can u please use proper grammar that people can understand? Also try rebooting minecraft and then go to .minecraft/logs/latest.log

**Comment by lc67846** [comment]
i did
