### ISSUE TITLE
cursor does not appear

### ISSUE THREAD

**Issue by BmoreKarl** [Delta2Force/MCVmComputers#172]
i am running ubuntu on the vm, i cannot see any cursor but it affects things on screen when i click. can i fix this by customizing my cursor?

**Comment by Busaruba2011** [comment]
This is a problem with Linux guests in general.

**Comment by BmoreKarl** [comment]
do you know of any solution?

**Comment by Busaruba2011** [comment]
There isn't one

**Comment by BmoreKarl** [comment]
ok

**Comment by y2k04** [comment]
Duplicate of #14
