### ISSUE TITLE
Please add .ova support

### ISSUE THREAD

**Issue by MC-HackerTech** [Delta2Force/MCVmComputers#173]
I always shrugged to install a OS virtual box then I found about .ova which is much easier to setup so please add .ova support (if you can :])

**Comment by CoccodrillooXDS** [comment]
You may import an appliance on VirtualBox manually and rename it to "VmComputersVm". Be aware that you will need to move the hdd location to the mod folder you have chosen in the initial setup.

**Comment by MC-HackerTech** [comment]
???

**Comment by CoccodrillooXDS** [comment]
.ova format is an appliance. You need to open it with VirtualBox and rename the virtual machine name after you imported it.

**Comment by MC-HackerTech** [comment]
Ok
