### ISSUE TITLE
Suggestion: Bitcoin Cash address

### ISSUE THREAD

**Issue by RowanSkie** [Delta2Force/MCVmComputers#176]
I've noticed you have a Bitcoin address. How about cryptocurrency addresses for the following coins?

Bitcoin Cash
Monero
Ethereum

It might also help more as Bitcoin Cash users are actually giving out Bitcoin Cash as tips. Its usage is peer-to-peer electronic cash, after all, not a store of value like Bitcoin.

It also helps mitigate any potential fees taken by Bitcoin's network when someone wants to actually donate in cryptocurrency.

**Comment by Delta2Force** [comment]
I added a bitcoin cash address, I'll add the other ones in the next few days!
