### ISSUE TITLE
Issue getting past 2/5 on mac

### ISSUE THREAD

**Issue by zirdum** [Delta2Force/MCVmComputers#18]
Thank you for adding mac support!

I'm having an issue on screen 2/5.
<img width="1367" alt="Screen Shot 2020-06-15 at 9 25 02 AM" src="https://user-images.githubusercontent.com/30192872/84682332-592e2c80-aeea-11ea-9deb-434f6c302e5e.png">

The path appears to be correct (I can go to it and see all the virtualbox files), but I can't use keyboard nor mouse to click on the Next button to proceed.

**Comment by Delta2Force** [comment]
Oh my god I’m sorry I had an oversight in the code for page 2/5, it’s looking for the windows files not the Mac ones... Should be fixed in no time.

**Comment by zirdum** [comment]
I'd like to donate to the cause... is there a paypal link I could send a few bucks to? (you should post it on your main page... I'm sure others would love to donate as well)

**Comment by Delta2Force** [comment]
Really? That’s awesome. Seriously, that’s really cool. The fact that you enjoy this so much that you would want to donate makes me really happy.

Do you know any platforms where underage people (me, 15 years old) could accept donations?

**Comment by zirdum** [comment]
Hmm... that is a dilemma. In the US there are some things like a CapitalOne 360 “Money” account, but you're most likely still going to need an adult to be the primary on the account with you as a secondary.

Here's a link I found that might be helpful but I can't personally speak for any of these: https://www.makeuseof.com/tag/paypal-alternatives-teenagers/

**Comment by Delta2Force** [comment]
I will release this as 1.2.3, you will be able to download it on here in about 10 mins

**Comment by Delta2Force** [comment]
What is your Reddit username? Asking so that we can continue the conversation outside of GitHub

**Comment by zirdum** [comment]
> What is your Reddit username? Asking so that we can continue the conversation outside of GitHub

It's God_TM
