### ISSUE TITLE
clicking on any screen crashes minecraft

### ISSUE THREAD

**Issue by alexvermaning0** [Delta2Force/MCVmComputers#184]
latest virtualbox (6.1.18)
latest mod 1.4.15
latest fabric 0.11.3
Latest FabricAPI 0.32.5
minecraft 1.16.5
Logs: [CrashLog](https://pastebin.com/UzsUGyd2) [latest.log](https://pastebin.com/DKC8AsAM)
the mod works perfectly the vm starts and everything. the only issue i have is if i click on the monitor, tv or crt it crashes the game.
the screens display the vm perfectly. as soon as you click it it crashes you.

**Comment by Delta2Force** [comment]
What Java version do you have? The important line here is this:
`java.lang.NoSuchMethodError: java.nio.DoubleBuffer.clear()Ljava/nio/DoubleBuffer;`
I also read online that this could be caused by compiling the mod with the wrong JDK version. I'll investigate more later. But for now, please just say your Java version :)

**Comment by Steve1150** [comment]
Not sure if this helps but i have the same issue and i'm running Java 8

**Comment by anh0516** [comment]
I'm experiencing the same issue on Ubuntu 20.10 using OpenJDK 8. As soon as I try and click on the VM it crashes Minecraft and hard poweroffs the VM. (It doesn't say aborted) Same exact Java error too.

**Comment by 7idge** [comment]
I'm also experiencing this. Same java error. I'm on Arch Linux (rolling) using OpenJDK 15. Same problems as @anh0516

**Comment by alexvermaning0** [comment]
Im running Openadopt Java 8 64 bit from ninite.com

**Comment by Delta2Force** [comment]
Everyone, please try the new release on github/curseforge. I changed the OpenJDK version on my machine from OpenJDK 11 to OpenJDK 8 and it should now work correctly.

**Comment by alexvermaning0** [comment]
it works,
no issues encounterd
