### ISSUE TITLE
FATAL: No Bootable Mediums found! System halted

### ISSUE THREAD

**Issue by f0x4wd** [Delta2Force/MCVmComputers#194]
whenever i try turning on the pc, the screen alway says "FATAL: No Bootable Mediums found! System halted" i had w2k3sp2_3959_usa_x64fre_spcd.iso basically a free windows xp iso from microsoft.com

**Comment by Busaruba2011** [comment]
That iso is just a service pack, not the os. For the os iso, I use the
software section of malwat.ch (the owner of the site is a youtuber called
enderman)

**Comment by f0x4wd** [comment]
oh ok
