### ISSUE TITLE
Can't get passed setup

### ISSUE THREAD

**Issue by YoItsOJ** [Delta2Force/MCVmComputers#197]
Hello! I have had some issues with the mod when trying to go through setup. Despite having fresh installs, running default directories, checking files, and even following a tutorial, I still get the same error:

![image](https://user-images.githubusercontent.com/75389344/114595466-69bf4880-9c5c-11eb-8d93-9fc3f9466e44.png)

Here is the log (At least that's what I think it is) 

[latest.log](https://github.com/Delta2Force/MCVmComputers/files/6305660/latest.log)

I took a look inside the log and I think I know the issue.
I have 2 drives, an SSD and a Hard Drive. my SSD is very small and most of the time it's almost full, so I use my 1TB Hard Drive to install apps and program files. That's what I did when I installed Virtual Box too.

When windows was set up, it set my SSD as the default C: OS Drive, which most all apps use for default installation, so I have to change the install directory to the D: (The Hard Drive)

So when I went through the setup process, I changed the file directory to go to my Hard Drive rather than the default SSD.

However, I think that MCVm doesn't give a fuck, and just decides to run through to the C: Directory, eventually finding nothing.

Log String:

> [13:27:05] [main/INFO]: [STDERR]: java.io.IOException: Cannot run program "C:\Program Files\Oracle\VirtualBox\vboxmanage.exe": CreateProcess error=2, The system cannot find the file specified

That should be going to my D: drive, but as you can see it's not.

Please let me know how to fix this as I would really like to experience this mod.

EDIT: Alright, I went on an older version of the mod and it worked, so I think it's a bug with the newer version.

**Comment by dotada** [comment]
Same with me, can you pls tell me which version of the mod you got?

**Comment by SuNG0D** [comment]
Same, I don't know how to fix it because I'm a script kiddie

**Comment by OJgaming97** [comment]
> Same with me, can you pls tell me which version of the mod you got?


> Same, I don't know how to fix it because I'm a script kiddie

Latest (1.4.5fix)

**Comment by ItsK1tty** [comment]
A symlink might do.

**Comment by ItsK1tty** [comment]
Just tried a symlink - works fine. Here's a quick guide:
Launch CMD with admin rights - those needed to make a folder in Program files
```
mkdir "C:\Program Files\Oracle\Virtualbox"
cd "C:\Program Files\Oracle"
mklink /J Virtualbox "path to the virtualbox installation folder"
```

**Comment by benjaYTn** [comment]
> Just tried a symlink - works fine. Here's a quick guide:
> Launch CMD with admin rights - those needed to make a folder in Program files
> 
> ```
> mkdir "C:\Program Files\Oracle"
> mkdir "C:\Program Files\Oracle\Virtualbox"
> cd "C:\Program Files\Oracle"
> mklink /J Virtualbox "path to the virtualbox installation folder"
> ```

it just says to me "cannot create a file that already exists"

**Comment by ItsK1tty** [comment]
> > Just tried a symlink - works fine. Here's a quick guide:
> > Launch CMD with admin rights - those needed to make a folder in Program files
> > 
> > ```
> > mkdir "C:\Program Files\Oracle"
> > mkdir "C:\Program Files\Oracle\Virtualbox"
> > cd "C:\Program Files\Oracle"
> > mklink /J Virtualbox "path to the virtualbox installation folder"
> > ```
> 
> it just says to me "cannot create a file that already exists"

On what step?

**Comment by benjaYTn** [comment]
> > > Just tried a symlink - works fine. Here's a quick guide:
> > > Launch CMD with admin rights - those needed to make a folder in Program files
> > > ```
> > > mkdir "C:\Program Files\Oracle"
> > > mkdir "C:\Program Files\Oracle\Virtualbox"
> > > cd "C:\Program Files\Oracle"
> > > mklink /J Virtualbox "path to the virtualbox installation folder"
> > > ```
> > 
> > 
> > it just says to me "cannot create a file that already exists"
> 
> On what step?

the mklink one, this is the command i used that doesn't work: `mklink /J Virtualbox "D:\Programs\Virtualbox"`

**Comment by ItsK1tty** [comment]
my bad. Do rmdir "C:\Program Files\Oracle\Virtualbox" and then mklink. Edited my post before so other users don't get confused

**Comment by ItsK1tty** [comment]
@y2k04 it appears this issue has been resolved as no replies were posted in two years. how about closing it?

**Comment by y2k04** [comment]
Okay
