### ISSUE TITLE
Game Crashes after clicking on the Monitor

### ISSUE THREAD

**Issue by Healthboost213** [Delta2Force/MCVmComputers#200]
My game crashes after clicking on the monitor. 

Crash Log:

https://pastebin.com/y1VDXTwW

**Comment by RTRIOS** [comment]
This happens to me too

**Comment by Healthboost213** [comment]
Use the most recent update stating “Emergency Update” it fixes the issue for the most part.

**Comment by y2k04** [comment]
Duplicate of #184
