### ISSUE TITLE
How do I run it on the server

### ISSUE THREAD

**Issue by Piskopatmusa** [Delta2Force/MCVmComputers#205]
My friends and I want to do movies and stuff.

**Comment by CubiePlays** [comment]
IDK if you can watch movies with this mod because you need to put VHDs in the server files and it needs VirtualBox in that server.

**Comment by Delta2Force** [comment]
No, the way multiplayer works is that the VM runs on one person's client and the screen gets transferred. Audio doesn't get transferred though.
