### ISSUE TITLE
Vboxwebsrv issue

### ISSUE THREAD

**Issue by ADawsome** [Delta2Force/MCVmComputers#206]
This issue is the same as #197, except i'm running this on a Ubuntu Desktop 20.04.2 LTS. Is it possible that the mod can't find Virtual Box because Linux has a different file path for it?

**Comment by Busaruba2011** [comment]
Is that an Ubuntu host or vm?

**Comment by ADawsome** [comment]
It's an ubuntu host.

**Comment by Delta2Force** [comment]
It doesn't work over paths, it should work if vboxwebsrv is on your PATH environment variable. You can check this by entering vboxwebsrv into your terminal.

**Comment by ADawsome** [comment]
Is it IPC socket path?

**Comment by y2k04** [comment]
Duplicate of #197
