### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by CatProgrammer-Java** [Delta2Force/MCVmComputers#210]
Game hanging on "All values valid. Attempting to start VirtualBox."

**Comment by Delta2Force** [comment]
Can you upload your log (`.minecraft/logs/latest.log`) to a website like pastebin or something like that after this occurs?

**Comment by ModDownloader** [comment]
> Can you upload your log (`.minecraft/logs/latest.log`) to a website like pastebin or something like that after this occurs?

I send it on next week, please do not close

**Comment by ModDownloader** [comment]
https://pastebin.com/H8yKhsUS

**Comment by Delta2Force** [comment]
Which version of Java are you running? In Java 8 this shouldn't be a problem

**Comment by ModDownloader** [comment]
16

**Comment by Delta2Force** [comment]
When the mod version for Minecraft 1.17 comes out this bug will be fixed

**Comment by y2k04** [comment]
Duplicate of #197
