### ISSUE TITLE
vboxwebsrv is still running error

### ISSUE THREAD

**Issue by Tonkyboi1** [Delta2Force/MCVmComputers#218]
So... It says vboxwebsrv is still running but it isn't. Look at the images
![1-help](https://user-images.githubusercontent.com/87203360/126243728-80b2744f-b3d8-407d-81a3-7689b70d58dd.png)
and this:
![EE](https://user-images.githubusercontent.com/87203360/126243799-23f21864-9a41-4402-984d-dd3b5b34f79b.png)
(Also the log):
[2021-07-19-1.log](https://github.com/Delta2Force/MCVmComputers/files/6844574/2021-07-19-1.log)

**Comment by Delta2Force** [comment]
It's saying `C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe`, you probably specified a wrong path? Which version of VirtualBox did you try to pass to the mod?

**Comment by Tonkyboi1** [comment]
> It's saying `C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe`, you probably specified a wrong path? Which version of VirtualBox did you try to pass to the mod?

6.1 (also sry for the late reply my pc was broken for a while)

**Comment by MegaSa1nt** [comment]
try downloading 6.1.26 without editing path to install

**Comment by 581121** [comment]
i am getting the same error and before you say put C:\Program Files\Oracle\VirtualBox\vboxwebsrv.exe I already tried it but its says directory doesn't exist and vm version is 6.1.32 or something

**Comment by 581121** [comment]
please respond fast

**Comment by Dragonlord1005** [comment]
virtualbox renamed it to VBoxWebSrv or something like that, he needs to fix it @581121

**Comment by philix1** [comment]
i have problem to

**Comment by y2k04** [comment]
Duplicate of #197
