### ISSUE TITLE
Servers!!!

### ISSUE THREAD

**Issue by towermom9** [Delta2Force/MCVmComputers#222]
Can this mod work in a linux container like a hosting platform?
If yes how to install the mod?
Wanting this for my smp server :)
1.16.5

**Comment by Delta2Force** [comment]
If you put the mod on the server, other people may see your screen when you start the vm. The vm will run on the client's pcs, not the server, so it should be all fine :D

**Comment by towermom9** [comment]
is there anyway to run the vm on the server side?

**Comment by Delta2Force** [comment]
No, at least not yet (if ever).

**Comment by thatcatdrout** [comment]
I found a solution. Install [this](https://fabricmc.net/use/?page=serverl) to the server. Then place the McVmComputers jar file in the mods directory. Hope this helps

**Comment by thatcatdrout** [comment]
I found a solution. Install [this](https://fabricmc.net/use/?page=server) to the server. Then just place the JAR files of Fabric API and McVmComputers to the mods directory on the server. **Hope this helps**

**Comment by y2k04** [comment]
Duplicate of #10
