### ISSUE TITLE
[Question] Does this work on multiplayer?

### ISSUE THREAD

**Issue by madmangenius5** [Delta2Force/MCVmComputers#232]

**Comment by KiaWeb** [comment]
Should be able to work on multiplayer, depending on Virtualbox, etc.

**Comment by y2k04** [comment]
In version 1.4 (for Minecraft 1.16.2), Delta2Force added the ability to see other people's screens.

**Comment by madmangenius5** [comment]
> 

I posted this over a year ago, you would've thought that I would've found the answer to my question in this time period, but no, y2k04 answered my question and now I know that I can use this on multiplayer on Minecraft version 1.16.2. Thank you.

**Comment by y2k04** [comment]
Glad I could help :)

**Comment by y2k04** [comment]
I'm taking over development for this project and have started rewriting it to use Java 17, Minecraft 1.19.2, and VirtualBox 7.0.4
(It previously used Java 8, Minecraft 1.16.2, and VirtualBox 6.1.x)

**Comment by y2k04** [comment]
Duplicate of #10
