### ISSUE TITLE
Failed to start virtualboy

### ISSUE THREAD

**Issue by mandarinka12051** [Delta2Force/MCVmComputers#234]
![image](https://user-images.githubusercontent.com/94446667/141966288-052a81d6-90b3-498f-ad57-95d3349507b3.png)

Please help me with this.

OS Version: Windows 10 Home 21H1
Virtualbox ver: 6.1.12
Minecraft ver: 1.16.5

**Comment by marcellubicukier** [comment]
same issue

**Comment by y2k04** [comment]
Duplicate of #197
