### ISSUE TITLE
Failed To Start  Viurtalbox (Same With Others)

### ISSUE THREAD

**Issue by EAZYBLACK** [Delta2Force/MCVmComputers#237]
I see in task manager every starts ok vboxwebsrv start ok but it says this
windows 10 1909 May 2019 Update
Tried With VirtualBox 6.1.14 and 6.1.26 but doesnt work

**Comment by EAZYBLACK** [comment]
Solution found open virtual box first then minecraft and works

**Comment by y2k04** [comment]
Duplicate of #197
