### ISSUE TITLE
M O U S E (also, Minecraft is a crashoholic) 

### ISSUE THREAD

**Issue by gaussandhisgun** [Delta2Force/MCVmComputers#240]
how did noone try this before? so, get a computer mouse, put it in your offhand and just right click the floor. boom, nullpointer, game's gone. Your log is here 👉 https://katb.in/acuxalojura

**Comment by PokeyManatee4** [comment]
MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump Is In Your Flags Thats Why  and you applied a broken texture pack

**Comment by PokeyManatee4** [comment]
@gaussandhisgun
