### ISSUE TITLE
VboxWebServ already running error

### ISSUE THREAD

**Issue by TruefateYT** [Delta2Force/MCVmComputers#241]
Everytime i keep trying to setup it says Vbox WebServ is running

I installed old versions of virtual and that still didn't work

Please tell what i'm doing wrong

**Comment by TruefateYT** [comment]
Everytime i keep trying to setup it says Vbox WebServ is running

I installed old versions of virtual and that still didn't work 


Please tell what i'm doing wrong

**Comment by asgwrd** [comment]
Im having the same issue

**Comment by y2k04** [comment]
Refer to #253
