### ISSUE TITLE
Isos

### ISSUE THREAD

**Issue by OFFYS20** [Delta2Force/MCVmComputers#246]
Can someone how to get isos and where put it?

**Comment by PokeyManatee4** [comment]
We Can Tell You Where To Put Them But Give Hell No That's Pirating and Im afraid Thats Against The Law

**Comment by Ameenbro123** [comment]
You can get linux ISO's for free such as debian or ubuntu, the windows 10 ISO is also free I believe you just need to install it with the right software. Here are some links for ISO's.
**Ubuntu**: https://ubuntu.com/download/desktop
**Fedora**: https://getfedora.org/
**Debian**: https://www.debian.org/distrib/

**Comment by y2k04** [comment]
There is also [WinWorldPC](https://winworldpc.com)
