### ISSUE TITLE
Crash when adding motherboard

### ISSUE THREAD

**Issue by ThatCosmicPanda** [Delta2Force/MCVmComputers#25]
I'm getting this crash every single time I try to add a motherboard. After the crash, trying to right-click the same PC case instantly crashes the game.

https://pastebin.com/1up2AnVN

**Comment by Delta2Force** [comment]
You have an uninitialized hard drive in your inventory, which due to a bug makes this happen. Initialize the hard drive and it should work. I will fix this bug ASAP.

**Comment by Delta2Force** [comment]
Fixed in version 1.3.1
