### ISSUE TITLE
Is it possible to make it compatible with VMware?

### ISSUE THREAD

**Issue by 4beep** [Delta2Force/MCVmComputers#251]

**Comment by 4winyt** [comment]
I mean, most of the code would have to be rewritten.

**Comment by 4beep** [comment]
> I mean, most of the code would have to be rewritten.

Yes, But atleast the virtualization would be WAY MORE FASTER

**Comment by y2k04** [comment]
I would have to look, but I am pretty sure there is a headless mode for VMware. Otherwise, the next best option is QEMU

**Comment by 4beep** [comment]
If theres how, please make aw tutorial on how to make it!

**Comment by y2k04** [comment]
After further reading on APIs and possible solutions, VMware will not be supported due to the lack of interaction it can have.

**Comment by y2k04** [comment]
Also, duplicate of #258
