### ISSUE TITLE
vboxwebsrv is still running error

### ISSUE THREAD

**Issue by 581121** [Delta2Force/MCVmComputers#253]
![126243728-80b2744f-b3d8-407d-81a3-7689b70d58dd](https://user-images.githubusercontent.com/79969558/159148590-98113b17-49c8-4eb2-91b9-db1c32e5fcaa.png)

**Comment by FuriousG** [comment]
Im having the same problem
 I dont know how to fix it, But you can reinstall Virtualbox to your main disk drive (where your windows, minecraft etc is installed) and then change the directorys in the vmcomputers to match where you reinstalled virtual box (this worked for me)

**Comment by y2k04** [comment]
Could you please send the log file?

**Comment by y2k04** [comment]
Duplicate of #197
