### ISSUE TITLE
CPU Cores is only limited to single core

### ISSUE THREAD

**Issue by BiruLangit8176** [Delta2Force/MCVmComputers#259]

**Comment by TCAtrevor** [comment]
A fix for this was made, and even pulled, but never released in a version officially. I made a release of the version with functioning multi-core if you are interested.
https://github.com/TCAtrevor/MCVmComputers/releases/latest

**Comment by y2k04** [comment]
We will officially support this soon. Now adding to to-do list.

**Comment by y2k04** [comment]
Duplicate of #161
