### ISSUE TITLE
Just saying: could this be ported to 1.18.1?

### ISSUE THREAD

**Issue by dmj-games** [Delta2Force/MCVmComputers#261]

**Comment by KingTino104** [comment]
he is probably gonna start it from scratch
for newer versions.

**Comment by y2k04** [comment]
Rewrite in progress for 1.19.2 (after I get it into a working state, I will attempt to port to older versions)
![image](https://user-images.githubusercontent.com/29883287/205475486-306d0f1f-bc40-47d8-afbd-2c19387b36bb.png)

**Comment by dmj-games** [comment]
YAAAAAAAAAAAAAAAAYYYYYYYYYYYYYYYYYY!!!!

**Comment by y2k04** [comment]
Related to #143
