### ISSUE TITLE
Nothing Showing Up on Display When PC Started With an Iso

### ISSUE THREAD

**Issue by ghost** [Delta2Force/MCVmComputers#262]
I am using minecraft 1.16.5. I use Arch Linux, and my client is ATLauncher. I have fabric version 1.16.5 and I have follow the tutorials exactly how they were executed help please?

**Comment by y2k04** [comment]
Could you please explain this with more detail and screenshots of VirtualBox and Minecraft running the mod at the same time?

**Comment by y2k04** [comment]
Duplicate of #45
