### ISSUE TITLE
Forge 

### ISSUE THREAD

**Issue by Cielse** [Delta2Force/MCVmComputers#266]
forge pls

**Comment by Natemo6348** [comment]
I would also like a Forge version, but if it's possible, I have no idea. Also would like to know if I could eventually be able to use virtualbox 7 with this mod.

**Comment by y2k04** [comment]
@Cielse That is on the todo now. Thanks!

@Natemo6348 #280

**Comment by y2k04** [comment]
Duplicate of #249
