### ISSUE TITLE
Support for Virtualbox installations that are in another folder?

### ISSUE THREAD

**Issue by studiotea** [Delta2Force/MCVmComputers#273]
It appears MCVmComputers directly uses the default folder, but while installing Virtualbox you can choose a folder to install Virtualbox into

Putting the folder in the textbox in the MCVmComputers's setup doesn't change anything.

**Comment by studiotea** [comment]
Nevermind, there's another issue addressing this.

**Comment by y2k04** [comment]
Duplicate of #11

**Comment by y2k04** [comment]
Related to #5
