### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by ImAQwertyGuy** [Delta2Force/MCVmComputers#281]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Remove mod 'VM Computers' (mcvmcomputers) 1.4.15 (/Users/abdullah/Library/Application Support/easymc-launcher/minecraft/mods/mcvmcomputers-1.4.15.jar).
	 - Replace 'OpenJDK 64-Bit Server VM' (java) 8 with version 17 or later.
	 - Replace 'Minecraft' (minecraft) 1.16.5 with any version between 1.19.3- (inclusive) and 1.19.4- (exclusive).
Unmet dependency listing:
	 - Mod 'Fabric API' (fabric-api) 0.75.1+1.19.3 requires version 17 or later of 'OpenJDK 64-Bit Server VM' (java), but only the wrong version is present: 8!
	 - Mod 'Fabric API' (fabric-api) 0.75.1+1.19.3 requires any version between 1.19.3- (inclusive) and 1.19.4- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Command API (v2)' (fabric-command-api-v2) 2.2.1+3fc4752e85 requires any version between 1.19-alpha.22.11.a (inclusive) and 1.20- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Convention Tags' (fabric-convention-tags-v1) 1.2.2+8e4e694f85 requires version 1.18.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	 - Mod 'Fabric Sound API (v1)' (fabric-sound-api-v1) 1.0.8+75e9821185 requires version 1.19.2 or later of 'Minecraft' (minecraft), but only the wrong version is present: 1.16.5!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by y2k04** [comment]
You have installed mods for 1.19.2/1.19.3 on a 1.16.5 instance. Always read the popup.

**Comment by y2k04** [comment]
To give you a head start, here is what this is saying:
  - You are using Java 8 which is only required for legacy versions of Minecraft. Use Java 17 instead.
  - You have the incorrect Fabric API version. You downloaded it for 1.19.3 instead of 1.16.5.
  
https://fabricmc.net/wiki/install

**Comment by y2k04** [comment]
This is an invalid issue and is not the fault of this mod.

**Comment by ImAQwertyGuy** [comment]
I am using EasyMC Launcher which has Fabric built in. I have latest Java. Maybe it's the launcher's fault?

**Comment by y2k04** [comment]
> I am using EasyMC Launcher which has Fabric built in. I have latest Java. Maybe it's the launcher's fault?

Potentially. I use PrismLauncher, and if I want to use versions that use Java 8 (like 1.8.9) I will manually set it in the instance's config.
![image](https://user-images.githubusercontent.com/29883287/227046659-88fa976a-4d52-4d67-8882-df000db1dd10.png)
