### ISSUE TITLE
Softlock on fourth stage of the setup (Linux)

### ISSUE THREAD

**Issue by TheSystemGuy1337** [Delta2Force/MCVmComputers#285]
This is effectively abandonware and the only version I could find that offers better support doesn't have any compiled binaries available. I tried doing it myself and failed. Anyhow, I'm still going to speak to the brick wall. Any attempt to run this on Linux is moot and will end with a softlock, meaning that you can only run this on Windows. It's a shame that this is abandonware and doesn't work on Linux.

**Comment by Maks7594** [comment]
someone is making a remake for 1.17 and above, and also virtualbox 7.0.0 and above. so this bug might be fixed in the better version.

**Comment by y2k04** [comment]
I am going to delete my fork for 1.17 because we are completely rewriting it.

**Comment by TheSystemGuy1337** [comment]
This project is abandonware. No way in hell will this issue ever be fixed. Closing.
