### ISSUE TITLE
no internet

### ISSUE THREAD

**Issue by idkloasd** [Delta2Force/MCVmComputers#301]
so when i create a windows 10 or a windows 7 there is no internet for some reason but anything below vista has internet so if anyone knows what to do please tell me

**Comment by idkloasd** [comment]
oh wait i fixed it

**Comment by Coldinex** [comment]
how?

**Comment by idkloasd** [comment]
Hello the way i fixed it is i went to the settings of the vm then i clicked
network then in adapter type i chose intel pro 1000 mt desktop and i had
internet so yeah hopefully this helped
