### ISSUE TITLE
Question: Live Texture Rendering

### ISSUE THREAD

**Issue by alexstrov** [Delta2Force/MCVmComputers#41]
This is an excellent mod! I am looking through the code and one of the biggest nuggets from it is... how do you get the VirtualBox window to render as a live texture within Minecraft? 

What plugin, or where in the code is this happening?

**Comment by Delta2Force** [comment]
In mcvmcomputers.client.utils.VMRunnable, you can see the code that gets the image. It's actually just taking a screenshot every frame from the VM and putting it into a static variable which then gets uploaded to the GPU by the function "generatePCScreen" in  mcvmcomputers.client.ClientMod.
