### ISSUE TITLE
Your screen resolution is too high for a live feed to be sent to other players.

### ISSUE THREAD

**Issue by sabi1** [Delta2Force/MCVmComputers#42]
So for some reason, I am not able to See my screen because the Resolution is too hight ? Which resolution ? the Minecraft Resolution or the VM resolution ? My VM got a resolution of 800x
400 so im not really sure what I am doing wrong here...
![Anmerkung 2020-07-17 215447](https://user-images.githubusercontent.com/16332702/87826008-6d15d700-c878-11ea-8acf-5dd30d362fcb.png)

**Comment by Delta2Force** [comment]
You are supposed to be able to still see the screen when this happens, so this is a bug.

**Comment by Delta2Force** [comment]
Fixed in 1.4.5

**Comment by WoeyJonkers** [comment]
This bug is back on the latest version, 1.4.15
