### ISSUE TITLE
Can't select any ISO

### ISSUE THREAD

**Issue by Theo2473** [Delta2Force/MCVmComputers#43]
When I wanted to select an ISO none of them popup its just blank
And in some video I found they get the menu when they right-click the pc
Which I don't get why
![image](https://user-images.githubusercontent.com/68507273/87877445-a9634780-c9de-11ea-8369-f1cd01f561af.png)
![image](https://user-images.githubusercontent.com/68507273/87877467-d1eb4180-c9de-11ea-83e0-2affa296d2d0.png)

**Comment by Delta2Force** [comment]
Did you put your ISOs into your vm_computers directory? If you didn't change the location, it's supposed to be at .minecraft/vm_computers. You put the ISOs into vm_computers/isos.

**Comment by Delta2Force** [comment]
I'm just going to close this since I assume that it worked.
