### ISSUE TITLE
Flatscreen monitor isn't working for me

### ISSUE THREAD

**Issue by DannyTheGeek** [Delta2Force/MCVmComputers#45]

**Comment by Delta2Force** [comment]
What issue are you having? Is it just not being rendered or what do you mean?

**Comment by DannyTheGeek** [comment]
> What issue are you having? Is it just not being rendered or what do you mean?

When I turn on the PC, the flatscreen monitor doesn't display anything. But I tried with the TV and CRT, those do display the pc.

**Comment by DannyTheGeek** [comment]
Don't know what I did wrong last time, but I checked and it is indeed working.
