### ISSUE TITLE
Network?

### ISSUE THREAD

**Issue by DannyTheGeek** [Delta2Force/MCVmComputers#47]
Will you be planning to add network capabilities? Is that even possible?

**Comment by Delta2Force** [comment]
What do you mean by that? Currently it applies the VirtualBox default networking settings. Do you mean interaction with other computers on the same server?

**Comment by DannyTheGeek** [comment]
> What do you mean by that? Currently it applies the VirtualBox default networking settings. Do you mean interaction with other computers on the same server?

I meant as in internet. I couldn't access the internet due to a driver error, is that because of me and the ISO or VirtualBox?

**Comment by Delta2Force** [comment]
Could be VirtualBox. There should be a way to customize the settings the VM uses.

**Comment by DannyTheGeek** [comment]
Alright, thank you

**Comment by DannyTheGeek** [comment]
> Could be VirtualBox. There should be a way to customize the settings the VM uses.

Just checked, and I saw that the Network adapter was different. I switched it to a one that I know works, but after I booted up Minecraft it reset. Honestly don't know what to do, but thank you!

**Comment by adryd325** [comment]
I made a custom build of the mod which changed the OS type to "ubuntu" which defaults to a more compatible network adapter.

**Comment by CoccodrillooXDS** [comment]
(OT but not OT)
As network, you (@Delta2Force) could add a model of a router, wireless repeater etc. in game, that would be awesome.
[For OP: I don't have that problem since my Win 2000 vm works fine]

**Comment by Delta2Force** [comment]
Btw the network adapter is now not removed anymore (version 1.4.6)

**Comment by DannyTheGeek** [comment]
> Btw the network adapter is now not removed anymore (version 1.4.6)

That's awesome! Thank you!!
