### ISSUE TITLE
VM does not close if Minecraft crashes

### ISSUE THREAD

**Issue by ggtylerr** [Delta2Force/MCVmComputers#48]
If Minecraft crashes, VirtualBox doesn't close and remains running in the background. This is a huge issue, especially regarding performance, as most users won't actually know it's still running (_or worse still, know how to close it, since the only way to do so is through Task Manager or any similar method._)

**Comment by Delta2Force** [comment]
I always knew this existed, but I don’t really know how I should fix this

**Comment by DannyTheGeek** [comment]
This would make much sense as to why my computer gets a BSOD when Minecraft crashes. I haven't had Minecraft crash since I lowered the Max RAM usage

**Comment by BlueJay113** [comment]
> I always knew this existed, but I don’t really know how I should fix this

Runtime.getRuntime().exec("taskkill /F /IM VboxHeadless.exe")

**Comment by Delta2Force** [comment]
> > I always knew this existed, but I don’t really know how I should fix this
> 
> `Runtime.getRuntime().exec("taskkill /F /IM VboxHeadless.exe")`

Doesn’t work on Linux or Mac.

**Comment by CoccodrillooXDS** [comment]
> 
> 
> > > I always knew this existed, but I don’t really know how I should fix this
> > 
> > 
> > `Runtime.getRuntime().exec("taskkill /F /IM VboxHeadless.exe")`
> 
> Doesn’t work on Linux or Mac.

On Linux and Mac you have to do this command: (@Delta2Force)
` kill $(ps aux | grep '[V]BoxHeadless' | awk '{print $2}') `

**Comment by Delta2Force** [comment]
> If Minecraft crashes, VirtualBox doesn't close and remains running in the background. This is a huge issue, especially regarding performance, as most users won't actually know it's still running (_or worse still, know how to close it, since the only way to do so is through Task Manager or any similar method._)

In the qemu branch I implemented something for this, when the game crashes and prints the crash report I hook into it and shut the VM down
