### ISSUE TITLE
Mod cannot find VirtualBox with custom install directory

### ISSUE THREAD

**Issue by proton-c** [Delta2Force/MCVmComputers#5]
I'm running windows.

I installed VirtualBox in my D drive as opposed to my C drive (to save space) and it turns out that the mod was looking for VirtualBox in the C drive and I had to reinstall it. Would it be possible for the mod to find a custom install directory?

**Comment by Delta2Force** [comment]
Yeah, this definitely needs to be fixed. The windows patch was a quick fix, and stuff like this needs to be respected.

**Comment by Delta2Force** [comment]
Fixed in commit f8f83e0da727332d94962dc5660176fde6344837, aka version 1.2.1
