### ISSUE TITLE
[BUG] Unfocus combination and default max ram/vram don't save into the config file

### ISSUE THREAD

**Issue by CoccodrillooXDS** [Delta2Force/MCVmComputers#51]
Hi! I would like to change the default unfocus combination and max ram, but they don't save into the config file and every time I open Minecraft, I need to set again the unfocus combination and max ram.

**Comment by DannyTheGeek** [comment]
That's just the way that it boots up. It asks me every time, you're just going to have to put it in every time.

**Comment by Delta2Force** [comment]
This is not a bug, it's just not implemented yet

**Comment by Delta2Force** [comment]
Implemented in 1.4.6
