### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by ItsProyal** [Delta2Force/MCVmComputers#52]
I feel like its something im just blind and don't see the issue but each time I right-click on the pc case (Either case does it).

The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: net.minecraft.class_1087.method_24304()Z

Is there a fix to this or am I doing something wrong, as far as I know you right-click the pc case after placing it.

**Comment by Delta2Force** [comment]
You need to use the mod with **1.15.2**, you are probably using it with 1.15
