### ISSUE TITLE
Crashed while attempting to render PC Case Edit Screen

### ISSUE THREAD

**Issue by AshtonSnapp** [Delta2Force/MCVmComputers#54]
I have attached a crash log. I have no other mods installed other than Fabric and the Fabric API. I had grabbed parts out of the creative inventory and had placed down the PC case, when I right clicked it the game crashed.

[crash-2020-07-28_19.37.29-client.txt](https://github.com/Delta2Force/MCVmComputers/files/4991847/crash-2020-07-28_19.37.29-client.txt)

**Comment by Delta2Force** [comment]
You need to use Minecraft 1.15.2 with the mod, you are using Minecraft 1.15.
