### ISSUE TITLE
Not connecting to VirtualBox

### ISSUE THREAD

**Issue by SixTfour** [Delta2Force/MCVmComputers#6]
OS: `Ubuntu 20.04`
MCVmComputers Version: `1.2.0`
VirtualBoxVersion: `6.1.8`

Minecraft is getting hung up on the setup screen saying "All values valid. Attempting to start VirtualBox." It looks like it creates an instance at localhost:18083, but never actually connects.

https://github.com/Delta2Force/MCVmComputers/blob/c7847cce2b92ccbb0693885f9c8bee383fb48069/src/main/java/mcvmcomputers/gui/GuiSetup.java#L130-L144

**Comment by Delta2Force** [comment]
I don't have a clue what could be causing this.

**Comment by Delta2Force** [comment]
Can you reproduce the log and upload the log file?

**Comment by coolymike** [comment]
Same issue here, on Manjaro.
[latest.log](https://github.com/Delta2Force/MCVmComputers/files/4809913/latest.log)

**Comment by SixTfour** [comment]
Switching to Java 8 fixed this for me. I was using Java 11.

**Comment by carleuca** [comment]
How did you make it work? Im having the same issue here

**Comment by Delta2Force** [comment]
On curseforge the mod is listed as Java 8 only, @carleuca you need to install Java 8.
