### ISSUE TITLE
I cant start it???

### ISSUE THREAD

**Issue by moglol** [Delta2Force/MCVmComputers#69]
![image](https://user-images.githubusercontent.com/70176674/91101256-9affef80-e65e-11ea-83f0-904abce73f1c.png)
i get this error when i start it up it shuts down and does this

**Comment by moglol** [comment]
still happening

**Comment by ChrisChrome** [comment]
You have VirtualBox running right?

**Comment by moglol** [comment]
in the backround???

**Comment by moglol** [comment]
ill try and run it before the mod

**Comment by ChrisChrome** [comment]
Wait a second, it wouldnt let you in game if you didnt have it running

**Comment by moglol** [comment]
yea ik i just noticed i cant start the vm the game made in virtualbox 
![image](https://user-images.githubusercontent.com/70176674/91208839-bcb2b280-e702-11ea-93b9-93da029f03b7.png)

**Comment by moglol** [comment]
should i delete the vm? and let the game make a new one

**Comment by moglol** [comment]
i removed it and got a different error
![image](https://user-images.githubusercontent.com/70176674/91209565-d6a0c500-e703-11ea-958d-d36a35877bce.png)

**Comment by moglol** [comment]
it wont let me attatch right screenshot??

**Comment by moglol** [comment]
fixed it lol
![image](https://user-images.githubusercontent.com/70176674/91209834-38f9c580-e704-11ea-8fb2-16672a426281.png)

**Comment by CoccodrillooXDS** [comment]
Close Minecraft, delete the folder containing VmComputersVm in "C:\Users\Morgan\VirtualBox VMs\"

And try again

**Comment by moglol** [comment]
coccodrillo its still happining after what you said it just made a new vm

**Comment by CoccodrillooXDS** [comment]
What happens if you launch the VM from VirtualBox?

(Also, what version of VirtualBox do you have?)

**Comment by moglol** [comment]
it gives me an error and im on vbox v.6.1.8

(heres a screenshot of the error) 
![image](https://user-images.githubusercontent.com/70176674/91301123-511d2380-e79c-11ea-9fce-dec46c874ab9.png)

**Comment by moglol** [comment]
it workss now i updated vbox 
![image](https://user-images.githubusercontent.com/70176674/93233632-37577680-f773-11ea-8de1-9e10e5f3f4f5.png)

**Comment by y2k04** [comment]
Duplicate of #45
