### ISSUE TITLE
Right Clicking Computer case

### ISSUE THREAD

**Issue by RoboTiberius** [Delta2Force/MCVmComputers#7]
When I right-click on the computer case I crash here is the crash log, I think its my resource pack I did not have time to check:

[crash-2020-06-13_22.56.17-client.txt](https://github.com/Delta2Force/MCVmComputers/files/4775796/crash-2020-06-13_22.56.17-client.txt)

**Comment by Delta2Force** [comment]
What Minecraft version did you install the mod on?

**Comment by RoboTiberius** [comment]
1.15, Do I need to be in 1.15.2?

**Comment by Delta2Force** [comment]
Try it out in 1.15.2, if it works then I’ll have to change a lot of stuff to say that it only works with 1.15.2

**Comment by RoboTiberius** [comment]
It works on 1.15.2!

**Comment by Delta2Force** [comment]
So the mod only works on 1.15.2... I’m gonna update the pages.
