### ISSUE TITLE
Ubuntu won't do anything after boot

### ISSUE THREAD

**Issue by MariahJauregui** [Delta2Force/MCVmComputers#71]
Setting up ubuntu was fine, except no mouse cursor, but after it's setup, it's just black. It shows the ubuntu loading screen and then nothing.

**Comment by Delta2Force** [comment]
Huh. Do you see anything if you access the virtual machine directly through VirtualBox?

**Comment by MariahJauregui** [comment]
Yes

**Comment by Delta2Force** [comment]
So, you start the VM ingame -> the screen is black ingame -> you look at VirtualBox -> the screen is not black?

**Comment by MariahJauregui** [comment]
Yup

**Comment by MariahJauregui** [comment]
I'll have to check

**Comment by MariahJauregui** [comment]
It is black

**Comment by MariahJauregui** [comment]
It worked after I showed it in virtualbox and closed the virtualbox window

**Comment by MariahJauregui** [comment]
There's no mouse cursor

**Comment by Delta2Force** [comment]
Yeah the mouse cursor has been a problem for a while (#14)

**Comment by lc67846** [comment]
It Only Works On Windows Linux Only Has Post Coding Powers Windows Has More Post Processing

**Comment by Half-Life-3** [comment]
I had the same issue, but it appears to be a problem with VirtualBox rather than the mod... Ubuntu 20.04 will not boot in a headless VM when Guest Additions are installed. Uninstalling Guest Additions fixes the issue.

**Comment by y2k04** [comment]
Duplicate of #14
