### ISSUE TITLE
Unable to install Arch Linux / Ubuntu

### ISSUE THREAD

**Issue by yuukixdev** [Delta2Force/MCVmComputers#75]
Arch boot screen still works fine, but when installation started it just stuck at probing EDD

Ubuntu won't continue to installation and just stays black screen with a flashing underscore

Is this an issue or Linux is not supported? Since I can still install Ubuntu fine by setting OS to Ubuntu Linux on VirtualBox.

**Comment by Delta2Force** [comment]
You should be able to change the OS in VirtualBox to Linux and keep the type when you start it ingame

**Comment by Delta2Force** [comment]
Nope, nvm, it gets overwritten here: https://github.com/Delta2Force/MCVmComputers/blob/3535892f7a85ac590491e4a1aa15d0a3e31d03a4/src/main/java/mcvmcomputers/client/gui/GuiPCEditing.java#L570

**Comment by yuukixdev** [comment]
yeah, the VM changes back from my Ubuntu preset to Unknown x64
plus running Windows XP with 4 GB of ram gives me a very stuttery visual performance, is that an issue?

**Comment by yuukixdev** [comment]
#77 has added VM OS selection, this should probably fix the installation issue.
@Delta2Force please merge #77 into master branch thanks

**Comment by Delta2Force** [comment]
It has now been merged, so this problem should be gone with VM Computers 1.7.10.
