### ISSUE TITLE
Windows 95 has too much ram

### ISSUE THREAD

**Issue by terankly** [Delta2Force/MCVmComputers#76]
Because of Windows 95's limitations, you can't run it on a machine with 1 or more gigabytes of RAM. In addition whenever you set the VM to have a different amount of ram, it always resets to the ram in the game, making it impossible. You should add a 512 MB ram stick in the mod

**Comment by CoccodrillooXDS** [comment]
Hi 👋
Some new RAM sticks will be added to the mod soon ᵗᵐ. ☺️

**Comment by terankly** [comment]
thanks!
