### ISSUE TITLE
Suggestion for support for VMWare

### ISSUE THREAD

**Issue by Busaruba2011** [Delta2Force/MCVmComputers#80]
This isn't really a issue (if this is the wrong way to suggest something, please let me know) but lots of people use VMWare, so if you want to, maybe try and get VMWare working with it?

**Comment by CoccodrillooXDS** [comment]
Hi! 👋
I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
(@Delta2Force)

**Comment by Busaruba2011** [comment]
> Hi! 👋
> I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
> (@Delta2Force)

Ok, thanks. Just thought coz lots of people use VMWare

**Comment by BlueJay113** [comment]
> Hi! 👋
> I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
> (@Delta2Force)

@Busaruba2011 At this current moment, VMware doesn't have an API for Workstation Player. The only viable option at this point is QEMU, but we are all open to other suggestions for virtualisation software (preferrably light, such as on idle not using much cpu or memory when it isn't running anything)

**Comment by Busaruba2011** [comment]
> > Hi! 👋
> > I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
> > (@Delta2Force)
> 
> @Busaruba2011 At this current moment, VMware doesn't have an API for Workstation Player. The only viable option at this point is QEMU, but we are all open to other suggestions for virtualisation software (preferrably light, such as on idle not using much cpu or memory when it isn't running anything)

Ah, I see, thanks!

**Comment by Paranoid-OS** [comment]
> > Hi! 👋
> > I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
> > (@Delta2Force)
> 
> @Busaruba2011 At this current moment, VMware doesn't have an API for Workstation Player. The only viable option at this point is QEMU, but we are all open to other suggestions for virtualisation software (preferrably light, such as on idle not using much cpu or memory when it isn't running anything)

Is support for hyper-v possible?

**Comment by Busaruba2011** [comment]
> > > Hi! 👋
> > > I _don't think_ it's possible as **I** haven't found any way to interface with VMware,
> > > (@Delta2Force)
> > 
> > @Busaruba2011 At this current moment, VMware doesn't have an API for Workstation Player. The only viable option at this point is QEMU, but we are all open to other suggestions for virtualisation software (preferrably light, such as on idle not using much cpu or memory when it isn't running anything)
> 
> Is support for hyper-v possible?
> For Windows VMs, performance would be better
> https://github.com/Delta2Force/MCVmComputers/issues/78
> Also, regarding this issue, if hyper-v is supported, we can use remotefx 3d graphics adapter to enhance GPU performance greatly

I thought hyperv was only for Windows server oses?

**Comment by Paranoid-OS** [comment]
No, it can be run on Windows pro and higher

**Comment by Busaruba2011** [comment]
> No, it can be run on Windows 10 pro and higher
> I'm using it on Windows 10 Enterprise now

Ah, I see. I'm on windows 10 home

**Comment by BlueJay113** [comment]
@Delta2Force @CoccodrillooXDS 

I may have something here:
![image](https://i.imgur.com/yzEnigA.png)

**Comment by BlueJay113** [comment]
![image](https://user-images.githubusercontent.com/29883287/93542059-6e0fd580-f99b-11ea-89bb-4ab5246d923b.png)

**Comment by Busaruba2011** [comment]
> @Delta2Force @CoccodrillooXDS 
> 
> I may have something here:
> ![image](https://i.imgur.com/yzEnigA.png)

What's that?

**Comment by BlueJay113** [comment]
> > @Delta2Force @CoccodrillooXDS 
> > 
> > I may have something here:
> > ![image](https://i.imgur.com/yzEnigA.png)
> 
> What's that?

That is the VMWare CLI command line tool. Thought it might be useful to know about it. It's in the latest version of VMWare Workstation.

**Comment by Busaruba2011** [comment]
> > > @Delta2Force @CoccodrillooXDS 
> > > 
> > > I may have something here:
> > > ![image](https://i.imgur.com/yzEnigA.png)
> > 
> > What's that?
> 
> That is the VMWare command line tool. Thought it might be useful to know about it. It's in the latest version of VMWare Workstation.

How would that get it in Minecraft?

**Comment by BlueJay113** [comment]
> > > > @Delta2Force @CoccodrillooXDS 
> > > > 
> > > > I may have something here:
> > > > ![image](https://i.imgur.com/yzEnigA.png)
> > > 
> > > What's that?
> > 
> > That is the VMWare command line tool. Thought it might be useful to know about it. It's in the latest version of VMWare Workstation.
> 
> How would that get it in Minecraft?

Well, there might be a DLL you could interface or you could run commands in the background in Java? I don't know. I haven't looked into it in detail.

**Comment by Busaruba2011** [comment]
> > > > > @Delta2Force @CoccodrillooXDS 
> > > > > 
> > > > > I may have something here:
> > > > > ![image](https://i.imgur.com/yzEnigA.png)
> > > > 
> > > > What's that?
> > > 
> > > That is the VMWare command line tool. Thought it might be useful to know about it. It's in the latest version of VMWare Workstation.
> > 
> > How would that get it in Minecraft?
> 
> Well, there might be a DLL you could interface or you could run commands in the background in Java? I don't know. I haven't looked into it in detail.

Ah, ok

**Comment by Busaruba2011** [comment]
@Delta2Force @CoccodrillooXDS would this help: https://www.vmware.com/support/pubs/sdk_pubs.html
