### ISSUE TITLE
When creating hard drives, mod takes space left on C: drive, and not the drive that the VHD folder is in

### ISSUE THREAD

**Issue by robert-banks** [Delta2Force/MCVmComputers#89]
I have tried to make a 5 gigabytes drive, but it said that I don't have enough space for it, which was weird, as the drive I have my VHD folder on has 120 gigabytes free, I could only make a 2 gigabytes hard drive, which coincidentally is around the free space I have on my C: drive.

**Comment by Delta2Force** [comment]
Added in 1.4.11
