### ISSUE TITLE
Can not unfocus the screen with the key combination shown.

### ISSUE THREAD

**Issue by Hacker1245** [Delta2Force/MCVmComputers#9]
I'm using Manjaro, and I can not unfocus the screen. I tried it multiple times, it just does not seem to go through.

**Comment by Delta2Force** [comment]
That's bizarre. I'm on manjaro too and it works perfectly fine for me. I should add the ability to create a custom keybind for that though.

**Comment by Hacker1245** [comment]
Hm, what DE are you using?

**Comment by Delta2Force** [comment]
XFCE

**Comment by Hacker1245** [comment]
I use KDE, maybe that is related?

**Comment by Delta2Force** [comment]
Could be, maybe right control isn't sent or the control keys are only sent as modkeys.

**Comment by Hacker1245** [comment]
Alright, will wait for the option to rebind the keys.

**Comment by Delta2Force** [comment]
Please reply if the newest release (Which will be 1.2.2) fixes your issue.

**Comment by Hacker1245** [comment]
Yep, this fixed it.

**Comment by Delta2Force** [comment]
Nice!
