### ISSUE TITLE
Make possible to change VM type?

### ISSUE THREAD

**Issue by Paranoid-OS** [Delta2Force/MCVmComputers#96]
Arch with KDE crashes when there is keyboard input, when VirtualBox VM type is "other"
It works fine when VM type is "Arch 64bit"
However, when starting the VM in Minecraft after changing the VM type, it doesn't boot up.

Can you make changing the VM type possible?

**Comment by CoccodrillooXDS** [comment]
Hi! 👋
Do you have the latest version of the mod?

**Comment by Paranoid-OS** [comment]
yes
Normally, should it work?

**Comment by CoccodrillooXDS** [comment]
Yes, it should.

**Comment by Paranoid-OS** [comment]
Okay, then I'll try with other VMs other than Arch and see what happens.
It may be my own .vdi that may be the problem

**Comment by CoccodrillooXDS** [comment]
Try deleting the VM from VirtualBox and let the game recreate it for you. Shutdown the vm from the mod, change the type from VirtualBox and start the vm again

**Comment by Paranoid-OS** [comment]
hmm, it works with Ubuntu
I guess either my Arch install was damaged or somehow Arch doesn't agree well.
Closing issue, sorry - I should have tested more
