### ISSUE TITLE
Wall TV not working at certain angles

### ISSUE THREAD

**Issue by Paranoid-OS** [Delta2Force/MCVmComputers#97]
![image](https://user-images.githubusercontent.com/62641568/93168988-16852600-f75f-11ea-98b8-47fb208088ba.png)
You can see that one isn't working, while the other is
My pc case is there, if that helps (I doubt it, but...)
![image](https://user-images.githubusercontent.com/62641568/93169131-66fc8380-f75f-11ea-92f0-6173d7d15d70.png)

**Comment by Paranoid-OS** [comment]
Mouse and keyboard capture works, input works too, with the dead TV

**Comment by Delta2Force** [comment]
Fixed in 1.4.12
